# Generated by Django 3.1.1 on 2020-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20201002_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karunacurrent',
            name='transaction_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Received', 'Received')], default='Submitted', max_length=10, verbose_name='Transaction status'),
        ),
        migrations.AlterField(
            model_name='karunacurrent',
            name='transaction_type',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Band', 'Bank'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Transaction type'),
        ),
    ]
