# Generated by Django 3.1.1 on 2020-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20201002_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karunacurrent',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipts/', verbose_name='Photo of receipt'),
        ),
    ]
