# Generated by Django 3.1.1 on 2021-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20201003_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karunacurrent',
            name='transaction_type',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Bank', 'Bank'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Transaction type'),
        ),
    ]
